# Generated by Django 3.2.16 on 2023-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='投票名稱')),
                ('content', models.CharField(max_length=200, verbose_name='內容概述')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='建立時間')),
                ('date_start', models.DateField(verbose_name='投票開始時間')),
            ],
        ),
        migrations.CreateModel(
            name='HouSyuanRen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=12, verbose_name='姓氏')),
                ('name', models.CharField(max_length=12, verbose_name='名稱')),
                ('birth', models.DateField(verbose_name='出生年月日')),
                ('gender', models.CharField(max_length=5, verbose_name='性別')),
                ('party', models.CharField(max_length=20, verbose_name='黨籍')),
                ('academy', models.TextField(max_length=100, verbose_name='學歷')),
                ('seniority', models.TextField(max_length=150, verbose_name='資歷')),
                ('politics', models.TextField(max_length=10000, verbose_name='政見')),
            ],
        ),
    ]
