# Generated by Django 3.2.16 on 2023-01-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_housyuanren_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='housyuanren',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=50, verbose_name='選舉名稱'),
        ),
        migrations.AlterField(
            model_name='housyuanren',
            name='birth',
            field=models.DateField(max_length=10, verbose_name='出生年月日'),
        ),
    ]
