# Generated by Django 3.2.16 on 2023-01-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230112_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housyuanren',
            name='academy',
            field=models.TextField(max_length=200, verbose_name='學歷'),
        ),
        migrations.AlterField(
            model_name='housyuanren',
            name='seniority',
            field=models.TextField(max_length=10000, verbose_name='資歷'),
        ),
    ]
