# Generated by Django 3.2.16 on 2023-01-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230115_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='content',
            field=models.TextField(max_length=200, verbose_name='內容概述'),
        ),
    ]
